version: '3.8'

services:
  dorisk:
    build: .
    container_name: dorisk_app
    restart: always
    ports:
      - "8050:8000"
    env_file:
      - backend/.env
    volumes:
      - ./data:/app/data
    environment:
      - PORT=8000
